# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ember CLI Deploy
tagline:          'Deploy pipeline for Ember apps'
description:      'A deployment pipeline for Ember CLI apps'
url:              https://github.com/ember-cli/ember-cli-deploy
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ember-cli/ember-cli-deploy

